language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
cache: pip
install:
  - pip install pytest pytest-cov coveralls
  - pip install -e .
script:
  - pytest --cov=bencoding/
after_success:
  coveralls
